export default [
  {
    email: 'christopher@chat.com',
    password: '?wqzA4?23Gs!?#gjD8Gc',
    creditPhotoAuthorId: '@chrisjoelcampbell',
    creditPhotoAuthorName: 'Christopher Campbell',
  },
  {
    email: 'joseph@chat.com',
    password: 'D*HUXqffJGq=?5pNcwXE',
    creditPhotoAuthorId: '@miracletwentyone',
    creditPhotoAuthorName: 'Joseph Gonzalez',
  },
  {
    email: 'petr@chat.com',
    password: '+4GgK@GM2dJqDM5SB?rW',
    creditPhotoAuthorId: '@sevcovic23',
    creditPhotoAuthorName: 'Petr Sevcovic',
  },
  {
    email: 'erik@chat.com',
    password: 'nB6RhaUy2pJLa6B4',
    creditPhotoAuthorId: '@erik_lucatero',
    creditPhotoAuthorName: 'Erik Lucatero',
  },
  {
    email: 'iryna@chat.com',
    password: '8Q_F=Xu^yFw75VcN',
    creditPhotoAuthorId: '@irynabs',
    creditPhotoAuthorName: 'Iryna Sydorenko',
  },
  {
    email: 'raoul@chat.com',
    password: 'tZ3PyVRbhK9==2GB',
    creditPhotoAuthorId: '@raouldroog',
    creditPhotoAuthorName: 'Raoul Droog',
  },
  {
    email: 'charles@chat.com',
    password: 'SuWbG9q*6k+@89E*',
    creditPhotoAuthorId: '@charlesdeluvio',
    creditPhotoAuthorName: 'Charles Deluvio',
  },
  {
    email: 'kim@chat.com',
    password: 'SxHEZfde3F?wPu!w',
    creditPhotoAuthorId: '@kimberly123',
    creditPhotoAuthorName: 'Kim Carpenter',
  },
  {
    email: 'melina@chat.com',
    password: 'qCL^4dava%CWQ7T?',
    creditPhotoAuthorId: '@melinacesarini',
    creditPhotoAuthorName: 'Melina Cesarini',
  },
  {
    email: 'angelina@chat.com',
    password: 'wRXMJzb^^f9gqVWb',
    creditPhotoAuthorId: '@bebachka',
    creditPhotoAuthorName: 'Angelina',
  },
  {
    email: 'ian@chat.com',
    password: 'XrT+d+Bh^Q6?tbFg',
    creditPhotoAuthorId: '@sadswim',
    creditPhotoAuthorName: 'ian dooley',
  },
  {
    email: 'autumn@chat.com',
    password: 'Pb4zD3E7S6^STcDs',
    creditPhotoAuthorId: '@auttgood',
    creditPhotoAuthorName: 'Autumn Goodman',
  },
  {
    email: 'vince@chat.com',
    password: '5my-cX6C%UxJ@Fcy',
    creditPhotoAuthorId: '@vincefleming',
    creditPhotoAuthorName: 'Vince Fleming',
  },
  {
    email: 'hermes@chat.com',
    password: '$=g_zw&7UppbR$sG',
    creditPhotoAuthorId: '@hermez777',
    creditPhotoAuthorName: 'Hermes Rivera',
  },
  {
    email: 'mitchell@chat.com',
    password: 'NTsfz6%PP^dE$uQj',
    creditPhotoAuthorId: '@griestprojects',
    creditPhotoAuthorName: 'Mitchell Griest',
  },
  {
    email: 'manja@chat.com',
    password: '5X%r_UULEAg&$B%V',
    creditPhotoAuthorId: '@madhatterzone',
    creditPhotoAuthorName: 'Manja Vitolic',
  },
  {
    email: 'alex@chat.com',
    password: 'zCPG7=bt3TB^=fe%',
    creditPhotoAuthorId: '@alexiby',
    creditPhotoAuthorName: 'Alex Iby',
  },
  {
    email: 'bishka@chat.com',
    password: 'dy9=H3G=?ND5fUws',
    creditPhotoAuthorId: '@bishka',
    creditPhotoAuthorName: 'Bishka Nguyen',
  },
  {
    email: 'averie@chat.com',
    password: 'JuAq%w#cPKr5YXe?',
    creditPhotoAuthorId: '@averieclaire',
    creditPhotoAuthorName: 'averie woodard',
  },
  {
    email: 'christian@chat.com',
    password: 'Z7dC6+QfvMDT=q79',
    creditPhotoAuthorId: '@christianbuehner',
    creditPhotoAuthorName: 'christian buehner',
  },
  {
    email: 'elijah@chat.com',
    password: '-KYB72=7?eX*A#t+',
    creditPhotoAuthorId: '@elijahdhiett',
    creditPhotoAuthorName: 'Elijah Hiett',
  },
  {
    email: 'brooke@chat.com',
    password: 'zJ&QN+5D^LZD5zm7',
    creditPhotoAuthorId: '@brookecagle',
    creditPhotoAuthorName: 'Brooke Cagle',
  },
  {
    email: 'derick@chat.com',
    password: 'YY=*k&+T9XBx-N?Y',
    creditPhotoAuthorId: '@derickray',
    creditPhotoAuthorName: 'Derick McKinney',
  },
  {
    email: 'prince@chat.com',
    password: 'KskWT23aq$EHz!cD',
    creditPhotoAuthorId: '@princearkman',
    creditPhotoAuthorName: 'Prince Akachi',
  },
  {
    email: 'diego@chat.com',
    password: 'G^C&uzuR2WMvP$u_',
    creditPhotoAuthorId: '@ediegosanchez',
    creditPhotoAuthorName: 'DIEGO SANCHEZ',
  },
  {
    email: 'valeriia@chat.com',
    password: '!vka9BLa-ps8ktHA',
    creditPhotoAuthorId: '@lerakogan_art',
    creditPhotoAuthorName: 'Valeriia Kogan',
  },
  {
    email: 'sung@chat.com',
    password: '3mM7H%gXGdkSB@j@',
    creditPhotoAuthorId: '@sgwang0511',
    creditPhotoAuthorName: 'Sung Wang',
  },
  {
    email: 'nathan@chat.com',
    password: '+_uZb6xD&J6mXDs$',
    creditPhotoAuthorId: '@nathanfertig',
    creditPhotoAuthorName: 'Nathan Fertig',
  },
  {
    email: 'stefan@chat.com',
    password: 'rYSHAr!ZZ$j8F@p-',
    creditPhotoAuthorId: '@shttefan',
    creditPhotoAuthorName: 'SHTTEFAN',
  },
  {
    email: 'ayo@chat.com',
    password: '2GBEVxJC5B@m_te=',
    creditPhotoAuthorId: '@armedshutter',
    creditPhotoAuthorName: 'Ayo Ogunseinde',
  },
  {
    email: 'aiony@chat.com',
    password: 'b7VpGMej@-%#UD@*',
    creditPhotoAuthorId: '@aiony',
    creditPhotoAuthorName: 'Aiony Haust',
  },
  {
    email: 'sam@chat.com',
    password: 'jA8@rhb#y##6kyHj',
    creditPhotoAuthorId: '@samburriss',
    creditPhotoAuthorName: 'Sam Burriss',
  },
  {
    email: 'kanashi@chat.com',
    password: '7Gvpa&aYv3zMqBvH',
    creditPhotoAuthorId: '@kanashi',
    creditPhotoAuthorName: 'Kanashi',
  },
  {
    email: 'hunter@chat.com',
    password: 'Qr4M95bkZvrrnU_8',
    creditPhotoAuthorId: '@hun7er',
    creditPhotoAuthorName: 'Hunter Newton',
  },
  {
    email: 'allef@chat.com',
    password: 'H47=E2xBg=AB--Zv',
    creditPhotoAuthorId: '@seteph',
    creditPhotoAuthorName: 'Allef Vinicius',
  },
  {
    email: 'joshua@chat.com',
    password: 'w2#!YEGtVW?QBAa_',
    creditPhotoAuthorId: '@joaccord',
    creditPhotoAuthorName: 'Joshua Oluwagbemiga',
  },
  {
    email: 'midas@chat.com',
    password: 'EVc6k?Y52w6@5A--',
    creditPhotoAuthorId: '@midashofstra',
    creditPhotoAuthorName: 'Midas Hofstra',
  },
  {
    email: 'seth@chat.com',
    password: '9zeX4wq!3CUR^Dxz',
    creditPhotoAuthorId: '@sethdoylee',
    creditPhotoAuthorName: 'Seth Doyle',
  },
  {
    email: 'ivana@chat.com',
    password: '@4c5xgxc=duVrnQ_',
    creditPhotoAuthorId: '@von_co',
    creditPhotoAuthorName: 'Ivana Cajina',
  },
  {
    email: 'tristan@chat.com',
    password: 'GHjqdLzy#$nz+z3C',
    creditPhotoAuthorId: '@tristandixon',
    creditPhotoAuthorName: 'Tristan Dixon',
  },
  {
    email: 'dima@chat.com',
    password: 'Jf$^*s#v=YL8QYAD',
    creditPhotoAuthorId: '@dimadallacqua',
    creditPhotoAuthorName: 'Dima DallAcqua',
  },
  {
    email: 'ben@chat.com',
    password: '85tMxx*V8bKYzX^K',
    creditPhotoAuthorId: '@brokenlenscap',
    creditPhotoAuthorName: 'Ben Parker',
  },
  {
    email: 'rohan@chat.com',
    password: 'DgPc4n-sT7nt9f*T',
    creditPhotoAuthorId: '@rohan_g',
    creditPhotoAuthorName: 'Rohan G',
  },
  {
    email: 'nick@chat.com',
    password: '*#Y&z!KGp!WGH53T',
    creditPhotoAuthorId: '@nickdepartee',
    creditPhotoAuthorName: 'Nick de Partee',
  },
  {
    email: 'cedric@chat.com',
    password: 'A_9nhZ68PbRAUjDr',
    creditPhotoAuthorId: '@cedric_photography',
    creditPhotoAuthorName: 'Cédric VT',
  },
  {
    email: 'jayson@chat.com',
    password: 'dfK3&bQykxzs@m4w',
    creditPhotoAuthorId: '@jayson_hinrichsen',
    creditPhotoAuthorName: 'Jayson Hinrichsen',
  },
  {
    email: 'karsten@chat.com',
    password: 'k8VkD=#_U?j8B4GJ',
    creditPhotoAuthorId: '@karsten116',
    creditPhotoAuthorName: 'Karsten Winegeart',
  },
  {
    email: 'tom@chat.com',
    password: 'rj4Kns&CWWq@MWa?',
    creditPhotoAuthorId: '@tomrumble',
    creditPhotoAuthorName: 'Tom Rumble',
  },
];
